# Generated by Django 5.2.4 on 2025-08-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
