# Generated by Django 5.2.4 on 2025-08-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_remove_produto_disponivel_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=50),
        ),
    ]
