# Generated by Django 5.2.4 on 2025-08-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_produto_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=50)),
            ],
        ),
    ]
