# Generated by Django 5.2.4 on 2025-08-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_produto_descricao_produto_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
